%**************************************************************************
%
% Get Linear Matrices
%
%   Function computes "mass" and "stiffness" matrices for the linear part
%   of the wave equation problem.
%
%**************************************************************************

function [M, S, gM, gS] = getLinearMatrices(Mesh, n, c)

% Assembles the Mass and Stiffness matrices
dMesh = diff(Mesh);
S = spdiags( ...
    [ ...
    -1./dMesh(2:n) ...
    1./dMesh(1:n-1) + 1./dMesh(2:n) ...
    -1./dMesh(1:n-1) ...
    ], -1:1, n-1, n-1);
M = spdiags( ...
    [ ...
      dMesh(2:n) ...
      2*(dMesh(1:n-1)+dMesh(2:n)) ...
      dMesh(1:n-1) ...
    ]/(6 * c^2), ...
    -1:1, n-1, n-1);

% RHS terms
gS = -1./dMesh(1);
gM = dMesh(1)/6/c^2;

end

